[package]
name = "lios"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
limine = "0.2.0"
noto-sans-mono-bitmap = "0.3.0"
pic8259 = "0.11.0"
spin = "0.9.8"
uart_16550 = "0.3.0"
x86 = "0.52.0"
x86_64 = "0.15.1"
